version: '{build}'
environment:
  LIBVPX_BRANCH: v1.6.1
clone_script:
- cmd: >-
    git clone -q --branch=%LIBVPX_BRANCH% --depth 1 https://github.com/webmproject/libvpx.git

build_script:
- cmd: >-
    appveyor DownloadFile "https://cygwin.com/setup-x86_64.exe" -FileName "c:\cygwin-setup.exe"

    c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages make,automake,gcc,gcc-g++,perl,yasm

    set PATH=c:\cygwin-root\bin;%PATH%

    c:\cygwin-root\bin\sh -lc "cd $APPVEYOR_BUILD_FOLDER/libvpx/; ./configure --disable-docs --disable-examples --disable-shared --enable-static --target=x86_64-win64-gcc; make -j16"

    cd %APPVEYOR_BUILD_FOLDER%\libvpx

    dir /s/b *.exe

cache:
- c:\cygwin-setup-cache

test: off
artifacts:
- path: libvpx/vpxenc.exe
- path: libvpx/vpxdec.exe
