version: '{build}'
environment:
  LIBVPX_BRANCH: v1.6.1
clone_script:
- cmd: >-
    git clone -q --branch=%LIBVPX_BRANCH% --depth 1 https://github.com/webmproject/libvpx.git

build_script:
- cmd: >-
    appveyor DownloadFile "https://cygwin.com/setup-x86_64.exe" -FileName "c:\cygwin-setup.exe"

    c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages make,automake,gcc,gcc-g++

    set PATH=c:\cygwin-root\bin;c:\Perl;%PATH%

    c:\cygwin-root\bin\sh -lc "cd $APPVEYOR_BUILD_FOLDER; mkdir build; cd build; ../libvpx/configure --disable-examples --disable-install-docs --disable-vp9 --target=x86_64-win64-gcc; make"

    dir %APPVEYOR_BUILD_FOLDER%\build

cache:
- c:\cygwin-setup-cache

test: off
artifacts:
- path: build/config.log
