version: '{build}'
environment:
  LIBVPX_BRANCH: v1.6.1
clone_script:
- cmd: >-
    git clone -q --branch=%LIBVPX_BRANCH% --depth 1 https://github.com/webmproject/libvpx.git

build_script:
- cmd: >-
    set PATH=C:\cygwin64\bin;C:\Perl;%PATH%

    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build

    cd build

    ../libvpx/configure --disable-examples --disable-install-docs --disable-vp9 --target=x86_64-win32-gcc

    make

    dir

test: off
artifacts:
- path: build/config.log
