version: '{build}'
environment:
  LIBVPX_BRANCH: v1.6.1
clone_script:
- cmd: >-
    git clone -q --branch=%LIBVPX_BRANCH% --depth 1 https://github.com/webmproject/libvpx.git

build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    appveyor DownloadFile "https://raw.githubusercontent.com/altbdoor/vpxenc-exe/master/build.sh" -FileName "build.sh"

    appveyor DownloadFile "https://cygwin.com/setup-x86_64.exe" -FileName "c:\cygwin-setup.exe"

    c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages make,automake,gcc,gcc-g++,perl,yasm

    set PATH=c:\cygwin-root\bin;%PATH%

    c:\cygwin-root\bin\bash build.sh

    mkdir build

    robocopy libvpx build vpxenc.exe vpxdec.exe > nul

    robocopy c:\cygwin-root\bin build cygwin1.dll cygstdc++-6.dll > nul

    7z a bin.zip build

cache:
- c:\cygwin-setup-cache

test: off
artifacts:
- path: bin.zip
