version: '{build}'
environment:
  LIBVPX_BRANCH: v1.6.1
clone_script:
- cmd: >-
    git clone -q --branch=%LIBVPX_BRANCH% --depth 1 https://github.com/webmproject/libvpx.git

build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    appveyor DownloadFile "https://raw.githubusercontent.com/altbdoor/vpxenc-exe/master/build.sh" -FileName "build.sh"

    set PATH=c:\msys64\usr\bin;%PATH%

    c:\msys64\usr\bin\bash build.sh

cache:
- c:\pacman-cache

test: off
artifacts:
- path: binary.zip
